### ISSUE TITLE
Listing package requirements in Readme.md

### ISSUE THREAD

**Issue by ck37** [benmarwick/Interactive_PCA_Explorer#2]
Hi,

One minor thing that would be handy is to list the package requirements under the installation instructions. Since Shiny doesn't automatically install package requirements, it can take many iterations of calling runGithub() to find the next package that isn't installed, installing it, then trying again until finally all of the packages are installed and the app doesn't error out.

For me I had to install these packages which I didn't have already: DT, GGally, psych, and tabplot.

It seems pretty unfortunate that Shiny apps don't support listing package requirements in the DESCRIPTION file like a normal R package, so that any dependencies could be installed automatically when the app is run.

Thanks,
Chris

**Comment by benmarwick** [comment]
Thanks, that's a great observation and I agree an annoyance to have to repeatedly install packages. I've added code that will check if you have the necessary packages, and if not, download and install them all at  once. I've added a note to the readme to inform users about this also. Thanks again.
