### ISSUE TITLE
Filesize exceed the limit

### ISSUE THREAD

**Issue by hypotheses** [benmarwick/Interactive_PCA_Explorer#4]
I'm trying to run the Interactive PCA explorer on my data. The file size is around 50MB (a matrix of 2300x2300). There is an error pop-up that the file seems to be to large. Is there some where to fix this problem?

**Comment by benmarwick** [comment]
I'm not sure exactly, but it might best for you to look into solutions for PCA on large data frame, or working out of memory. This app is suited to small-medium datasets. It sounds like your data might be larger than typical. For example, you might find these relevant:

- https://stackoverflow.com/questions/12670972/doing-pca-on-very-large-data-set-in-r
- https://stackoverflow.com/questions/10718455/apply-pca-on-very-large-sparse-matrix?noredirect=1&lq=1

**Comment by hypotheses** [comment]
Thank you for your suggestion. 

I think this seems to fix my problem: https://stackoverflow.com/questions/18037737/how-to-change-maximum-upload-size-exceeded-restriction-in-shiny-and-save-user

> By default, Shiny limits file uploads to 5MB per file. You can modify this limit by using the shiny.maxRequestSize option. For example, adding options(shiny.maxRequestSize=30*1024^2) to the top of server.R would increase the limit to 30MB.
